export var ImageArray = [
    {
        "id": 50,
        "parent_id": 2,
        "name": "Shop By Brand",
        "is_active": "true",
        "position": 1,
        "level": 2,
        "product_count": 46,
        "img": "https://www.pulsecarshalton.co.uk/wp-content/uploads/2016/08/jk-placeholder-image.jpg",
        "placeHolder": "true",
        "children_data": [
            {
                "id": 51,
                "parent_id": 50,
                "name": "Prada",
                "is_active": "true",
                "position": 1,
                "level": 3,
                "product_count": 36,
                "img": "/pub/media/wysiwyg/smartwave/porto/theme_assets/images/prada.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 52,
                "parent_id": 50,
                "name": "Porsche Design",
                "is_active": "true",
                "position": 2,
                "level": 3,
                "product_count": 8,
                "img": "https://www.pulsecarshalton.co.uk/wp-content/uploads/2016/08/jk-placeholder-image.jpg",
                "placeHolder": "true",
                "children_data": []
            },
            {
                "id": 53,
                "parent_id": 50,
                "name": "Burberry",
                "is_active": "true",
                "position": 3,
                "level": 3,
                "product_count": 20,
                "img": "https://www.pulsecarshalton.co.uk/wp-content/uploads/2016/08/jk-placeholder-image.jpg",
                "placeHolder": "true",
                "children_data": []
            },
            {
                "id": 54,
                "parent_id": 50,
                "name": "Lacoste",
                "is_active": "true",
                "position": 4,
                "level": 3,
                "product_count": 2,
                "img": "/pub/media/wysiwyg/smartwave/porto/theme_assets/images/prada.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 55,
                "parent_id": 50,
                "name": "Bausch + Lomb",
                "is_active": "true",
                "position": 5,
                "level": 3,
                "product_count": 22,
                "img": "/pub/media/wysiwyg/smartwave/porto/theme_assets/images/prada.jpg",
                "placeHolder": "false",
                "children_data": []
            }
        ]
    },
    {
        "id": 4,
        "parent_id": 2,
        "name": "Contact Lenses",
        "is_active": "true",
        "position": 3,
        "level": 2,
        "product_count": 108,
        "img": "/pub/media/catalog/category/Contact-Lenses_5.jpg",
        "placeHolder": "false",
        "children_data": [
            {
                "id": 29,
                "parent_id": 4,
                "name": "Clear Prescription",
                "is_active": "true",
                "position": 1,
                "level": 3,
                "product_count": 12,
                "img": "/pub/media/catalog/category/image_2021_04_13T14_10_50_074Z.png",
                "placeHolder": "false",
                "children_data": [
                    {
                        "id": 78,
                        "parent_id": 29,
                        "name": "Daily",
                        "is_active": "true",
                        "position": 1,
                        "level": 4,
                        "product_count": 0,
                        "img": "https://www.pulsecarshalton.co.uk/wp-content/uploads/2016/08/jk-placeholder-image.jpg",
                        "placeHolder": "true",
                        "children_data": []
                    },
                    {
                        "id": 79,
                        "parent_id": 29,
                        "name": "Bi-Weekly",
                        "is_active": "true",
                        "position": 2,
                        "level": 4,
                        "product_count": 0,
                        "img": "https://www.pulsecarshalton.co.uk/wp-content/uploads/2016/08/jk-placeholder-image.jpg",
                        "placeHolder": "true",
                        "children_data": []
                    },
                    {
                        "id": 80,
                        "parent_id": 29,
                        "name": "Monthly",
                        "is_active": "true",
                        "position": 3,
                        "level": 4,
                        "product_count": 0,
                        "img": "https://www.pulsecarshalton.co.uk/wp-content/uploads/2016/08/jk-placeholder-image.jpg",
                        "placeHolder": "true",
                        "children_data": []
                    }
                ]
            },
            {
                "id": 30,
                "parent_id": 4,
                "name": "Color",
                "is_active": "true",
                "position": 2,
                "level": 3,
                "product_count": 73,
                "img": "/pub/media/catalog/category/Color_3.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 31,
                "parent_id": 4,
                "name": "Toric for Astigmatism",
                "is_active": "true",
                "position": 3,
                "level": 3,
                "product_count": 9,
                "img": "/pub/media/catalog/category/Toric-for-Astigmatism_6.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 32,
                "parent_id": 4,
                "name": "Multifocal for Presbyopia",
                "is_active": "true",
                "position": 4,
                "level": 3,
                "product_count": 4,
                "img": "/pub/media/catalog/category/image_2021_04_13T14_10_50_074Z.png",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 33,
                "parent_id": 4,
                "name": "Lens Solution",
                "is_active": "true",
                "position": 5,
                "level": 3,
                "product_count": 9,
                "img": "/pub/media/catalog/category/Lens-Solution_4.jpg",
                "placeHolder": "false",
                "children_data": []
            }
        ]
    },
    {
        "id": 24,
        "parent_id": 2,
        "name": "Computer Glasses",
        "is_active": "true",
        "position": 4,
        "level": 2,
        "product_count": 87,
        "img": '/pub/media/catalog/category/Computer-Glasses_6.jpg',
        "placeHolder": "false",
        "children_data": [
            {
                "id": 27,
                "parent_id": 24,
                "name": "Adults",
                "is_active": "true",
                "position": 1,
                "level": 3,
                "product_count": 34,
                "img": "/pub/media/catalog/category/Unisex_19.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 28,
                "parent_id": 24,
                "name": "Youth",
                "is_active": "true",
                "position": 2,
                "level": 3,
                "product_count": 29,
                "img": "/pub/media/catalog/category/Kids_20.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 81,
                "parent_id": 24,
                "is_active": "true",
                "position": 3,
                "level": 3,
                "product_count": 13,
                "name": "Accessories for Computer Glasses",
                "img": "/pub/media/catalog/category/banner2_1_.jpg",
                "placeHolder": "false",
                "children_data": [
                    {
                        "id": 82,
                        "parent_id": 81,
                        "name": "Cords",
                        "is_active": "true",
                        "position": 1,
                        "level": 4,
                        "product_count": 13,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    },
                    {
                        "id": 83,
                        "parent_id": 81,
                        "name": "Spray Cleaner",
                        "is_active": "true",
                        "position": 2,
                        "level": 4,
                        "product_count": 0,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    },
                    {
                        "id": 84,
                        "parent_id": 81,
                        "name": "Cases",
                        "is_active": "true",
                        "position": 3,
                        "level": 4,
                        "product_count": 0,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    }
                ]
            },
        ]
    },
    {
        "id": 25,
        "parent_id": 2,
        "name": "Eyeglasses",
        "is_active": "true",
        "position": 5,
        "level": 2,
        "product_count": 202,
        "img": "/pub/media/catalog/category/Reading-Glasses_5.jpg",
        "placeHolder": "false",
        "children_data": [
            {
                "id": 34,
                "parent_id": 25,
                "name": "Reading Glasses",
                "is_active": "true",
                "position": 1,
                "level": 3,
                "product_count": 28,
                "img": "/pub/media/catalog/category/Reading-Glasses_5.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 103,
                "parent_id": 25,
                "name": "Men",
                "is_active": "true",
                "position": 2,
                "level": 3,
                "product_count": 73,
                "img": "media/wysiwyg/smartwave/porto/theme_assets/images/resource/man-cat.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 104,
                "parent_id": 25,
                "name": "Women",
                "is_active": "true",
                "position": 3,
                "level": 3,
                "product_count": 39,
                "img": "media/wysiwyg/smartwave/porto/theme_assets/images/resource/women-cat.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 35,
                "parent_id": 25,
                "name": "Youth",
                "is_active": "true",
                "position": 4,
                "level": 3,
                "product_count": 23,
                "img": "media/wysiwyg/smartwave/porto/theme_assets/images/resource/kid-cat.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 105,
                "parent_id": 25,
                "name": "Frames Unisex",
                "is_active": "false",
                "position": 5,
                "level": 3,
                "product_count": 0,
                "img": "https://www.pulsecarshalton.co.uk/wp-content/uploads/2016/08/jk-placeholder-image.jpg",
                "placeHolder": "true",
                "children_data": []
            },
            {
                "id": 74,
                "parent_id": 25,
                "name": "Accessories For Eyeglasses",
                "is_active": "true",
                "position": 6,
                "level": 3,
                "product_count": 33,
                "img": "media/wysiwyg/smartwave/porto/theme_assets/images/resource/sunglasses-cat.jpg",
                "placeHolder": "false",
                "children_data": [
                    {
                        "id": 75,
                        "parent_id": 74,
                        "name": "Cords",
                        "is_active": "true",
                        "position": 1,
                        "level": 4,
                        "product_count": 27,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    },
                    {
                        "id": 76,
                        "parent_id": 74,
                        "name": "Spray Cleaner",
                        "is_active": "true",
                        "position": 2,
                        "level": 4,
                        "product_count": 2,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    },
                    {
                        "id": 77,
                        "parent_id": 74,
                        "name": "Cases",
                        "is_active": "true",
                        "position": 3,
                        "level": 4,
                        "product_count": 4,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    }
                ]
            }
        ]
    },
    {
        "id": 26,
        "parent_id": 2,
        "name": "Sunglasses",
        "is_active": "true",
        "position": 6,
        "level": 2,
        "product_count": 342,
        "img": "/pub/media/catalog/category/Sunglasses_6.jpg",
        "placeHolder": "false",
        "children_data": [
            {
                "id": 42,
                "parent_id": 26,
                "name": "Men",
                "is_active": "true",
                "position": 1,
                "level": 3,
                "product_count": 164,
                "img": "/pub/media/catalog/category/Men_12.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 43,
                "parent_id": 26,
                "name": "Women",
                "is_active": "true",
                "position": 2,
                "level": 3,
                "product_count": 220,
                "img": "/pub/media/catalog/category/Women_20.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 44,
                "parent_id": 26,
                "name": "Youth",
                "is_active": "true",
                "position": 3,
                "level": 3,
                "product_count": 27,
                "img": "/pub/media/catalog/category/Kids_16_1.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 73,
                "parent_id": 26,
                "name": "Unisex",
                "is_active": "false",
                "position": 4,
                "level": 3,
                "product_count": 2,
                "img": "https://www.pulsecarshalton.co.uk/wp-content/uploads/2016/08/jk-placeholder-image.jpg",
                "placeHolder": "true",
                "children_data": []
            },
            {
                "id": 45,
                "parent_id": 26,
                "name": "Accessories for Sunglasses",
                "is_active": "true",
                "position": 5,
                "level": 3,
                "product_count": 23,
                "img": "/pub/media/catalog/category/banner2_1_.jpg",
                "placeHolder": "false",
                "children_data": [
                    {
                        "id": 46,
                        "parent_id": 45,
                        "name": "Cords",
                        "is_active": "true",
                        "position": 1,
                        "level": 4,
                        "product_count": 1,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    },
                    {
                        "id": 47,
                        "parent_id": 45,
                        "name": "Spray Cleaner",
                        "is_active": "true",
                        "position": 2,
                        "level": 4,
                        "product_count": 0,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    },
                    {
                        "id": 48,
                        "parent_id": 45,
                        "name": "Cases",
                        "is_active": "true",
                        "position": 3,
                        "level": 4,
                        "product_count": 12,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    },
                    {
                        "id": 49,
                        "parent_id": 45,
                        "name": "Gift Cards",
                        "is_active": "true",
                        "position": 4,
                        "level": 4,
                        "product_count": 1,
                        "img": "/pub/media/catalog/category/banner2_1_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    },
                    {
                        "id": 96,
                        "parent_id": 45,
                        "name": "Safety Glasses",
                        "is_active": "true",
                        "position": 5,
                        "level": 4,
                        "product_count": 7,
                        "img": "/pub/media/catalog/category/saftey_.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    },
                    {
                        "id": 97,
                        "parent_id": 45,
                        "name": "Swimming Goggles",
                        "is_active": "true",
                        "position": 6,
                        "level": 4,
                        "product_count": 2,
                        "img": "/pub/media/catalog/category/swimming_banner.jpg",
                        "placeHolder": "false",
                        "children_data": []
                    }
                ]
            }
        ]
    },
    {
        "id": 72,
        "parent_id": 2,
        "name": "Offers",
        "is_active": "true",
        "position": 7,
        "level": 2,
        "product_count": 6,
        "img": "/pub/media/catalog/category/OffersBanners_AJO-05.jpg",
        "placeHolder": "false",
        "children_data": []
    },
    {
        "id": 89,
        "parent_id": 2,
        "name": "Others",
        "is_active": "true",
        "position": 8,
        "level": 2,
        "product_count": 81,
        "img": "https://www.pulsecarshalton.co.uk/wp-content/uploads/2016/08/jk-placeholder-image.jpg",
        "placeHolder": "true",
        "children_data": []
    },
    {
        "id": 102,
        "parent_id": 2,
        "name": "Accessories",
        "is_active": "true",
        "position": 9,
        "level": 2,
        "product_count": 47,
        "img": "/pub/media/catalog/category/banner2_1_.jpg",
        "placeHolder": "false",
        "children_data": [
            {
                "id": 122,
                "parent_id": 102,
                "name": "CORDS",
                "is_active": "true",
                "position": 1,
                "level": 3,
                "product_count": 20,
                "img": "/pub/media/catalog/category/banner2_1_.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 123,
                "parent_id": 102,
                "name": "SPRAY CLEANER",
                "is_active": "true",
                "position": 2,
                "level": 3,
                "product_count": 1,
                "img": "/pub/media/catalog/category/banner2_1_.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 124,
                "parent_id": 102,
                "name": "CASES",
                "is_active": "true",
                "position": 3,
                "level": 3,
                "product_count": 16,
                "img": "/pub/media/catalog/category/banner2_1_.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 125,
                "parent_id": 102,
                "name": "GIFT CARDS",
                "is_active": "true",
                "position": 4,
                "level": 3,
                "product_count": 1,
                "img": "/pub/media/catalog/category/banner2_1_.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 126,
                "parent_id": 102,
                "name": "SAFETY GLASSES",
                "is_active": "true",
                "position": 5,
                "level": 3,
                "product_count": 7,
                "img": "/pub/media/catalog/category/saftey_.jpg",
                "placeHolder": "false",
                "children_data": []
            },
            {
                "id": 127,
                "parent_id": 102,
                "name": "SWIMMING GOGGLES",
                "is_active": "true",
                "position": 6,
                "level": 3,
                "product_count": 2,
                "img": "/pub/media/catalog/category/swimming_banner.jpg",
                "placeHolder": "false",
                "children_data": []
            }
        ]
    },
]